# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TBC_User_auth.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(811, 586)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Header = QtWidgets.QLabel(self.centralwidget)
        self.Header.setGeometry(QtCore.QRect(180, 50, 441, 91))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Header.setFont(font)
        self.Header.setAlignment(QtCore.Qt.AlignCenter)
        self.Header.setObjectName("Header")
        self.Mail_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Mail_input.setGeometry(QtCore.QRect(310, 170, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.Mail_input.setFont(font)
        self.Mail_input.setObjectName("Mail_input")
        self.Pass_input = QtWidgets.QLineEdit(self.centralwidget)
        self.Pass_input.setGeometry(QtCore.QRect(310, 240, 191, 31))
        self.Pass_input.setEchoMode(QtWidgets.QLineEdit.Password)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        self.Pass_input.setFont(font)
        self.Pass_input.setObjectName("Pass_input")
        self.Mail_error = QtWidgets.QLabel(self.centralwidget)
        self.Mail_error.setGeometry(QtCore.QRect(310, 150, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.Mail_error.setFont(font)
        self.Mail_error.setText("")
        self.Mail_error.setObjectName("Mail_error")
        self.Pass_error = QtWidgets.QLabel(self.centralwidget)
        self.Pass_error.setGeometry(QtCore.QRect(310, 220, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        self.Pass_error.setFont(font)
        self.Pass_error.setText("")
        self.Pass_error.setObjectName("Pass_error")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 320, 151, 71))
        self.pushButton.clicked.connect(self.press)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.NewWin = QtWidgets.QStackedWidget(self.centralwidget)
        self.NewWin.setGeometry(QtCore.QRect(740, 440, 120, 80))
        self.NewWin.setObjectName("NewWin")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.NewWin.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.Congrat = QtWidgets.QLabel(self.page_2)
        self.Congrat.setGeometry(QtCore.QRect(10, 30, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(16)
        self.Congrat.setFont(font)
        self.Congrat.setText("")
        self.Congrat.setObjectName("Congrat")
        self.NewWin.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 811, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.NewWin.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def press(self):
        if self.Mail_input.text() == "admin" and self.Pass_input.text() == "admin123":
            self.NewWin.setGeometry(0, 0, 811, 586)
            self.Congrat.setText("You Are Logged In !")
            self.Congrat.setGeometry(290, 200, 151, 91)
            self.Congrat.adjustSize()
            self.NewWin.setStyleSheet("background-color: white;")


        elif self.Mail_input.text() == "admin" and self.Pass_input.text() != "admin123":
            self.Pass_error.setText("Incorrect")
            self.Pass_error.adjustSize()
        elif self.Mail_input.text() != "admin" and self.Pass_input.text() == "admin123":
            self.Mail_error.setText("Incorrect")
            self.Mail_error.adjustSize()
        else:
            self.Mail_error.setText("Incorrect")
            self.Pass_error.setText("Incorrect")
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Authenticate"))
        self.Header.setText(_translate("MainWindow", "User Auth"))
        self.Mail_input.setPlaceholderText(_translate("MainWindow", "Enter Your Email"))
        self.Pass_input.setPlaceholderText(_translate("MainWindow", "Password"))
        self.pushButton.setText(_translate("MainWindow", "LOG IN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
